# Generated by Django 6.0.4 on 2026-04-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('raw_comments', models.TextField(blank=True)),
                ('cleaned_comments', models.TextField(blank=True)),
                ('augmented_comments', models.TextField(blank=True)),
                ('iqr_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
